#ifndef TREEFACE_JUCE_COMMON_H
#define TREEFACE_JUCE_COMMON_H

#define TREEFACE_JUCE_NAMESPACE_BEGIN namespace treejuce {
#define TREEFACE_JUCE_NAMESPACE_END }

#define JUCE_STRING_UTF_TYPE 8

#endif // TREEFACE_JUCE_COMMON_H
